export const categories = [
  "🏋️ Fitness",
  "🎵 Music",
  "🍔 Food",
  "🌅 Scenery",
  "📖 Reading",
  "🚴 Cycling",
  "🎥 Movies",
  "🚶 Walking",
  "🏞️ Beach",
  "🎨 Art/Creativity",
  "🐶 Animals",
  "🍕 Pizza",
  "🌌 Drive",
  "🎤 Singing",
  "🌺 Natural Beauty",
  "🎁 Gift",
  "🪅 Party",
  "🍹 Drinks",
  "🛒 Shopping",
  "🎮 Gaming",
  "📊 Productivity",
  "🙏 Gratitude",
  "🗣️ Socializing",
];
